create rule-028 (dev)
ActioFRM/rule-028 pull request #4
Opened 2021-10-14 17:56 UTC by theolextego

Development part or rule 028 without automated testing

2021-10-18 10:10 UTC, johanfol commented on .env.template
> +DATABASE_PASSWORD=$!prAtHe>Qh5X9D3
Please do not share tokens / passwords in ANYTHING we commit. 

```suggestion
DATABASE_PASSWORD=
```

2021-10-18 10:10 UTC, johanfol commented on .env.test
> +process.env.REST_PORT = 3000
I don't believe this file is required anymore. Please delete.

2021-10-18 10:10 UTC, johanfol commented on Dockerfile
> +ENV DATABASE_PASSWORD=123456
Please remove all passwords from PR.

2021-10-18 10:10 UTC, johanfol commented on Dockerfile
> +ENV DATABASE_URL=http://arangodb.frm:8529
nice use of internal names. This, however, is not the correct internal endpoint:

```suggestion
ENV DATABASE_URL=http://arango.development:8529
```

2021-10-18 10:10 UTC, johanfol commented on Dockerfile
> +ENV RULE_ENDPOINT=http://gateway.frm:8080/function/
Incorrect endpoint
```suggestion
ENV RULE_ENDPOINT=http://gateway.development:8080
```

2021-10-18 10:10 UTC, johanfol commented on Dockerfile
> +ENV APM_URL=http://apm-server-apm-server.frm:8200
Incorrect endpoint
```suggestion
ENV APM_URL=http://apm-server.development:8200
```

2021-10-18 10:10 UTC, johanfol commented on Dockerfile
> +ENV LOGSTASH_HOST=my-release-logstash.frm-meshed
Incorrect endpoint
```suggestion
ENV LOGSTASH_HOST=logstash.development:8080
```

2021-10-18 10:10 UTC, johanfol commented on Dockerfile
> +ENV TYPOLOGY_ENDPOINT=10.244.7.84
Don't believe this variable is required anymore, as this information is already in the Network Map

2021-10-18 11:44 UTC, joeygoksu commented on src/controllers/executeController.ts
> +const sendRuleResultToPypologyProcessor = async (resultMessage: ResultMessage) => {
Typo

2021-10-18 11:44 UTC, joeygoksu commented on src/controllers/executeController.ts
> +        // const typologyResponse = await axios.post(`${typology.host}/execute`, resultMessage);
Comment out

2021-10-19 11:21 UTC, joeygoksu commented on src/clients/arango-client.service.ts
> +      // console.log(`Query result: ${JSON.stringify(results)}`);
console.log

2021-10-21 06:06 UTC, joeygoksu requested changes

2021-10-21 06:06 UTC, joeygoksu commented on src/clients/arango-client.service.ts
> +    LoggerService.log('✅ ArangoDB connection is ready');
I think this was in a condition.
if(arangoconnected) print ...

2021-10-21 06:06 UTC, joeygoksu commented on src/clients/arango-client.service.ts
> +      console.log('Error while executing query from arango with message:', error, 'ArangoDBService');
console.logs need to be removed

2021-10-21 06:06 UTC, joeygoksu commented on src/controllers/healthCheckController.ts
> +  ctx.body = 'online';
The file is already in the controller folder. We don't need to `controller` name in the file name. Otherwise, it's just a duplication.
healthCheck.ts?

2021-10-21 06:06 UTC, joeygoksu commented on src/controllers/healthCheckController.ts
> +  ctx.body = 'online';
This should be `UP` instead of `online`

2021-10-21 06:06 UTC, joeygoksu commented on src/interfaces/iDBService.ts
> +/* eslint-disable */
We should not need to disable eslint completely.

2021-10-21 06:06 UTC, joeygoksu commented on src/router.ts
> +// health checks
No need for this comment line.

2021-10-21 06:06 UTC, joeygoksu commented on src/router.ts
> +// health checks
+ no need for yarn.lock file

2021-10-21 16:56 UTC, theolextego commented on __tests__/unit/logic.service.test.ts
> +      );
😊

2021-11-03 09:41 UTC, uche-lextego approved these changes
LGTM. Well done Theo

2021-11-03 11:04 UTC, merged